stages:
  data_ingestion:
    cmd: python -m cnn_classifier.pipeline.stage_01_data_ingestion

    deps:
      - src/cnn_classifier/pipeline/stage_01_data_ingestion.py
      - src/cnn_classifier/config/configuration.py
    outs:
      - artifacts/data_ingestion/kidney_dataset



  prepare_base_model:
    cmd: python -m cnn_classifier.pipeline.stage_02_base_model
    deps:
      - src/cnn_classifier/pipeline/stage_02_base_model.py
      - src/cnn_classifier/config/configuration.py

    params:
      - IMAGE_SIZE
      - WEIGHTS
      - INCLUDE_TOP
      - CLASSES
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python -m cnn_classifier.pipeline.stage_03_model_train

    deps:
        - src/cnn_classifier/pipeline/stage_03_model_train.py
        - src/cnn_classifier/config/configuration.py
        - artifacts/data_ingestion/kidney_dataset
        - artifacts/prepare_base_model
    
    params:
        - IMAGE_SIZE
        - BATCH_SIZE
        - EPOCHS
        - AUGMENTATION

    outs:
        - artifacts/training/trained_model.h5


  evalution:
    cmd: python -m cnn_classifier.pipeline.stage_04_model_evalution
    deps:
      - src/cnn_classifier/pipeline/stage_04_model_evalution.py
      - src/cnn_classifier/config/configuration.py
      - artifacts/training/trained_model.h5
      - artifacts/data_ingestion/kidney_dataset

    params:
      - IMAGE_SIZE
      - BATCH_SIZE

    metrics:
      - scores.json:
         cache: false
